const primaryBody = [
  {
    type: 'columns',
    count: 2,
    json_en: { type: "columns", content: [ { type: "column", content: [{type: "paragraph", content: [{type: "text", text: "English"}]}] } ] },
    content: [ // these are generated by extractBody for 'columns'
      {
        type: 'column',
        json_en: { type: "column", content: [{type: "paragraph", content: [{type: "text", text: "English"}]}] },
        content: [
           { type: "paragraph", en: "English", json_en: {type: "paragraph", content: [{type: "text", text: "English"}]} }
        ]
      }
    ]
  }
];

const secondaryBody = [
  {
    type: 'columns',
    count: 2,
    json_ar: { type: "columns", content: [ { type: "column", content: [{type: "paragraph", content: [{type: "text", text: "Arabic"}]}] } ] },
    content: [ // these are generated by extractBody for 'columns'
      {
        type: 'column',
        json_ar: { type: "column", content: [{type: "paragraph", content: [{type: "text", text: "Arabic"}]}] },
        content: [
           { type: "paragraph", ar: "Arabic", json_ar: {type: "paragraph", content: [{type: "text", text: "Arabic"}]} }
        ]
      }
    ]
  }
];

const mergedBody = [];
for (let i = 0; i < primaryBody.length; i++) {
  mergedBody.push({ ...(secondaryBody[i] || {}), ...(primaryBody[i] || {}) })
}

console.log(JSON.stringify(mergedBody, null, 2))
